version: 2

models:
  - name: dimAddress
    description: contains address info for the customers
  - name: dimCustomer
    description: contains detailed info about the customers
  - name: dimDate
    description: contains various date properties
  - name: dimOrderStatus
    description: contains info about order statuses
  - name: dimProduct
    description: contains info about products
  - name: dimSalesTerritory
    description: contains info about sales territories
  - name: fctSales
    description: contains sales metrics
  
  